FROM richarvey/php-apache-heroku:latest

# Salin kode proyek ke dalam server
COPY . /var/www/app

# Set environment variabel untuk Laravel
ENV WEB_DOCUMENT_ROOT /var/www/app/public
ENV APP_ENV production

# Jalankan composer
RUN composer install --no-dev --optimize-autoloader

# Beri izin akses folder storage
RUN chown -R www-data:www-data /var/www/app/storage /var/www/app/bootstrap/cache